package platform

// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: platform.proto_platform
// File Location: repo/Platform.master.repository.go

import (
	"github.com/jinzhu/gorm"
)

// MasterRepository for factory repository
type MasterRepository struct { 
	Platform		PlatformRepoService
}
var masterRepo *MasterRepository

// NewMasterRepoService for new repository event service
func NewMasterRepoService(db *gorm.DB) *MasterRepository {
	if masterRepo == nil {
		masterRepo = &MasterRepository{ 
			Platform:		NewPlatformRepoService(db),
		}
	}
	return masterRepo
}

