
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: platform.proto
package platform

import  (
	core "github.com/zokypesch/proto-lib/core"
	runtime "github.com/grpc-ecosystem/grpc-gateway/runtime"
)

const (
	Platform_Create = "/platform.Platform/Create"
	Platform_Get = "/platform.Platform/Get"
)

var (
	FullMethods = []string{
		Platform_Create,
		Platform_Get,
	}
)

func InitCallGRPC() error {
	forward_Platform_Create_0 = core.LocalForward
	forward_Platform_Get_0 = core.LocalForward
	runtime.HTTPError = core.CustomHTTPError

	return nil
}

